# This file contains the fastlane.tools configuration
   # You can find the documentation at https://docs.fastlane.tools
   #
   # For a list of all available actions, check out
   #
   #     https://docs.fastlane.tools/actions
   #
   # For a list of all available plugins, check out
   #
   #     https://docs.fastlane.tools/plugins/available-plugins
   #

   # Uncomment the line if you want fastlane to automatically update itself
   # update_fastlane
require 'dotenv'
Dotenv.load
   default_platform(:android)

   platform :android do
     desc "lane for android app distribution"
     lane :test do

        sh "flutter clean"
        sh "flutter build apk --release --flavor production -t lib/main_production.dart"
       firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],

      firebase_cli_token: ENV["GOOGLE_REFRESH_TOKEN"],

        testers: "abwalshykhmhmd990@gmail.com,belalscg@gmail.com",
        android_artifact_type:'APK',
        android_artifact_path:  "D:/android_projects/graduation_proj/build/app/outputs/apk/release/app-release.apk",
        release_notes:"last version",
       )

     end
   end